properties:
  commandName:
    type: string
    description: A short name describing command. It will be used insdie "bin/magento".
  commandDescription:
    type: string
    description: A short description explaining feature behind generated command.
templateInfo:
  description: This Template creates a crud module using uiComponents for Grid and Form.