type: module
description: This template creates an empty console command.
properties:
    commandName:
        type: string
        required: true
        description: A short name describing command. It will be used inside "bin/magento", e.g. "some-group:do-something".
    commandDescription:
        type: string
        required: true
        description: A short description explaining feature behind generated command.
    commandFilePath:
        type: string
        required: true
        description: Command file path (e.g. "DoSomething" or "SomeGroup/DoSomething").
