description: This template is used to create new section in existent tab of store configuration.
properties:
  id:
    type: string
    required: true
    description: Section ID
  label:
    type: string
    required: true
    description: Section label
  tab:
    type: string
    required: true
    description: Tab code
  sortOrder:
    type: string
    description: sortOrder argument value
  separator:
    type: boolean
    description: Add top separator?
    default: false
  showInDefault:
    type: boolean
    description: showInDefault argument value
    default: true
  showInWebsite:
    type: boolean
    description: showInWebsite argument value
    default: true
  showInStore:
    type: boolean
    description: showInStore argument value
    default: true
