description: This template is used to create new section in existent tab of store configuration.
properties:
  id:
    type: string
    description: Section ID
  separator:
    type: string
    description: Add top separator? (yes/no)
    default: no
  label:
    type: string
    description: Section label
  tab:
    type: string
    description: Tab code
  sortOrder:
    type: string
    description: sortOrder argument value