type: module
description: This template creates custom fields for quote and order
properties:
  fields:
    type: array
    required: true
    description: Define all database fields by filling property for each field
    children:
      name:
        type: string
        required: true
        description: Name of the field
      databaseType:
        type: choice
        options:
          - bigint
          - blob
          - boolean
          - date
          - datetime
          - decimal
          - double
          - float
          - int
          - smallint
          - text
          - timestamp
          - tinyint
          - varbinary
          - varchar
        description: Database type of field
      length:
        type: string
        description: For varchar and varbinary types, it is length of column, for int types, it is padding. If empty, will use default.
      nullable:
        type: boolean
        default: false
        description: Indicates whether column can be nullable.
      unsigned:
        type: boolean
        default: false
        description: For numeric data types, specifies whether the column can contain positive and negative values or only positive values.
      precision:
        type: string
        description: The number of allowed digits in a real data type. If empty, will use default.
      scale:
        type: string
        description: The number of digits after the decimal in a real data type. If empty, will use default.
