properties:
  viewModelName:
    type: string
    description: A short name describing view model
templateInfo:
  description: "This template is used to create a view model and phtml template file for it.\n
                It should be used if you simply need to inject your business logic into template file.\n
                If you need to add some customizations to block processing, use \"block\" template instead."