description: 'This template creates event observer for given event code with needed files: events.xml and Observer class.'
properties:
  scope:
    type: choice
    options:
      - global
      - frontend
      - adminhtml
    description: Scope of the observer
  eventName:
    type: string
    required: true
    description: Event code that is beeing listened
  observerName:
    type: string
    required: true
    description: A short name describing observer
