type: module
description: Creates a 1 to 1 relation. Works only with entities from the module for now. Entities must be created before.
afterGenerate: "1. After creating or changing db_schema.xml, please generate db_schema_whitelist.json file:\n
                \n
                bin/magento setup:db-declaration:generate-whitelist --module-name {{ vendorName|pascal }}_{{ moduleName|pascal }}"
properties:
    entityName:
        type: string
        required: true
        description: Entity name
    entity2Name:
        type: string
        required: true
        description: Related entity name
    onDelete:
        type: choice
        options:
            - CASCADE
            - SET NULL
            - NO ACTION
        default: CASCADE
        description: Foreign key trigger
