type: root
description: 'This template is used to create basic configurations needed to start a custom theme.'
afterGenerate: "1. To apply changes please run setup upgrade command:\n
                \n
                bin/magento setup:upgrade"
properties:
  vendorName:
    type: string
    required: true
    default: Orba
    description: Typically a company name
  themeName:
    type: string
    required: true
    default: base
    description: A short name describing theme
  parent:
    type: choice
    options:
      - Magento/blank
      - Magento/luma
      - other
    description: Parent theme
  parentName:
    type: string
    required: true
    description: Parent theme name
    depend:
        parent: other
  assignTo:
    type: choice
    options:
        - default
        - website
        - store
        - none
    default: default
    description: The scope to which new theme will be assigned. Use "none" if you don't want to assign it anywhere.
  websiteCode:
    type: string
    required: true
    description: Code of the website to which new theme will be assigned
    depend:
        assignTo: website
  storeCode:
    type: string
    required: true
    description: Code of the store to which new theme will be assigned
    depend:
        assignTo: store
