type: module
description: This template is used to create new config field for already existent group of store configuration. It also creates config value getter in Config model.
properties:
  sectionId:
    type: string
    required: true
    description: ID of config section
  groupId:
    type: string
    required: true
    description: ID of config group
  id:
    type: string
    required: true
    description: Field ID
  label:
    type: string
    required: true
    description: Field label
  comment:
    type: string
    description: Field comment
  type:
    type: choice
    options:
      - button
      - checkbox
      - checkboxes
      - column
      - date
      - editablemultiselect
      - editor
      - fieldset
      - file
      - gallery
      - hidden
      - image
      - imagefile
      - label
      - link
      - multiline
      - multiselect
      - note
      - obscure
      - password
      - radio
      - radios
      - reset
      - select
      - submit
      - text
      - textarea
      - time
    description: Attribute type
    default: text
  sortOrder:
    type: string
    description: Sort order value
  showInDefault:
    type: boolean
    description: Should field be visible in default config scope?
    default: true
  showInWebsite:
    type: boolean
    description: Should field be visible in website scope?
    default: true
  showInStore:
    type: boolean
    description: Should field be visible in store scope?
    default: true
  canRestore:
    type: boolean
    description: Could default value be restored?
    default: true
  sourceModel:
    type: string
    description: Source Model of field
  validate:
    type: string
    description: Validation classes separated with space
  dependencyPath:
    type: string
    description: Path to the config field on which this field depends
  dependencyValue:
    type: string
    description: Value of the config field on which this field depends (fill in only if the fieldDependencyPath property was filled in)
  configScope:
    type: choice
    options:
      - store
      - website
      - default
    description: Scope of config field used by value getter
    default: website
  defaultValue:
    type: string
    description: Default config value
