description: This template is used to create new config field for already existent group of store configuration. It also creates config value getter in Config model.
properties:
  sectionId:
    type: string
    description: ID of config section
  groupId:
    type: string
    description: ID of config group
  configScope:
    type: string
    description: Scope of config field used by value getter (store, website, default)
    default: website
  fieldId:
    type: string
    description: Field ID
  fieldLabel:
    type: string
    description: Field label
  fieldComment:
    type: string
    description: Field comment (optional)
  fieldSourceModel:
    type: string
    description: Source Model of field (optional)
  fieldValidate:
    type: string
    description: Validation classes separated with space (optional)
  fieldDependencyPath:
    type: string
    description: Path to the config field on which this field depends (optional)
  fieldDependencyValue:
    type: string
    description: Value of the config field on which this field depends (fill in only if the fieldDependencyPath property was filled in)
  fieldType:
    type: string
    description: Type argument value
    default: text
  fieldSortOrder:
    type: string
    description: sortOrder argument value
  fieldShowInDefault:
    type: boolean
    description: showInDefault argument value
    default: true
  fieldShowInWebsite:
    type: boolean
    description: showInWebsite argument value
    default: true
  fieldShowInStore:
    type: boolean
    description: showInStore argument value
    default: true