description: This template is used to create basic configuration needed to start a custom module.
properties:
  vendorName:
    type: string
    default: Orba
    description: Typically a company name
  moduleName:
    type: string
    description: A short name describing module