type: basic
description: 'This template is used to create basic configuration needed to start a custom module.'
properties:
  vendorName:
    type: string
    required: true
    default: Orba
    description: Typically a company name
  moduleName:
    type: string
    required: true
    description: A short name describing module
  phpVersion:
    type: string
    required: true
    default: "~7.4.0"
    description: PHP version used in composer.json file
