type: module
description: "This template is used to create a JS mixin.\n"
afterGenerate: "1. Add custom logic to your freshly generated JS mixin in:\n
                \nview/{{ area }}/web/js/{{ originalModule|kebab }}-mixin.js\n"
properties:
    type:
        type: choice
        options:
            - plain
            - jQuery widget
            - component
        description: JS Mixin type
    area:
        type: choice
        options:
            - base
            - frontend
            - adminhtml
        default: base
        description: Area in which module will be used
    originalModule:
        type: string
        required: true
        description: Full path or alias from requirejs-config
    extendMethod:
        type: bool
        required: true
        default: false
        description: Should method extend an original method. If not, new one will be added
    methodName:
        type: string
        required: true
        description: Method name
