services:
  _defaults:
    autowire: true

  Symfony\Component\Filesystem\Filesystem:
    class: '\Symfony\Component\Filesystem\Filesystem'

  Symfony\Component\Yaml\Parser:
    class: '\Symfony\Component\Yaml\Parser'

  Orba\Magento2Codegen\:
    resource: '../src/Orba/Magento2Codegen'

  Orba\Magento2Codegen\Application:
    public: true

  Orba\Magento2Codegen\Input\Input:
    public: true

  Orba\Magento2Codegen\Service\FileMergerFactory:
    calls:
      -
        - addMerger
        -
          - '/^di\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/preference': 'for'
              '/config/(type|virtualType)': 'name'
              '/config/(type|virtualType)/plugin': 'name'
              '/config/(type|virtualType)/arguments/argument': 'name'
              '/config/(type|virtualType)/arguments/argument(/item)+': 'name'
            typeAttributeName: 'xsi:type'
      -
        - addMerger
        -
          - '/^db_schema\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/schema/table': 'name'
              '/schema/table/column': 'name'
              '/schema/table/constraint': 'referenceId'
              '/schema/table/index': 'referenceId'
              '/schema/table/index/column': 'name'
              '/schema/table/constraint/column': 'name'
      -
        - addMerger
        -
          - '/^.*\.xml/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'

  Orba\Magento2Codegen\Service\FileMerger\XmlMerger:
    shared: false

  Orba\Magento2Codegen\Command\Template\GenerateCommand:
    arguments:
      $inputValidators:
        - '@Orba\Magento2Codegen\Service\Input\RootDirValidator'

  Orba\Magento2Codegen\Service\TemplateProcessorInterface:
    class: '\Orba\Magento2Codegen\Service\TwigTemplateProcessor'

  Orba\Magento2Codegen\Service\Twig\FiltersExtension:
    arguments:
      $filters:
        camel: '@Orba\Magento2Codegen\Service\StringFilter\CamelCaseFilter'
        pascal: '@Orba\Magento2Codegen\Service\StringFilter\PascalCaseFilter'
        snake: '@Orba\Magento2Codegen\Service\StringFilter\SnakeCaseFilter'
        kebab: '@Orba\Magento2Codegen\Service\StringFilter\KebabCaseFilter'