services:
  _defaults:
    autowire: true

  Symfony\Component\Filesystem\Filesystem:
    class: '\Symfony\Component\Filesystem\Filesystem'

  Symfony\Component\Yaml\Parser:
    class: '\Symfony\Component\Yaml\Parser'

  Symfony\Component\Config\Definition\Processor:
    class: '\Symfony\Component\Config\Definition\Processor'

  Orba\Magento2Codegen\:
    resource: '../src/Orba/Magento2Codegen'
    exclude: '../src/Orba/Magento2Codegen/Test'

  Orba\Magento2Codegen\Application:
    public: true

  Orba\Magento2Codegen\Service\IO:
    public: true

  Orba\Magento2Codegen\Service\FileMergerFactory:
    calls:
      -
        - addMerger
        -
          - '/^[\s\S]*\\di\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/preference': 'for'
              '/config/(type|virtualType)': 'name'
              '/config/(type|virtualType)/plugin': 'name'
              '/config/(type|virtualType)/arguments/argument': 'name'
              '/config/(type|virtualType)/arguments/argument(/item)+': 'name'
            typeAttributeName: 'xsi:type'
      -
        - addMerger
        -
          - '/^[\s\S]*\\db_schema\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/schema/table': 'name'
              '/schema/table/column': 'name'
              '/schema/table/constraint': 'referenceId'
              '/schema/table/index': 'referenceId'
              '/schema/table/index/column': 'name'
              '/schema/table/constraint/column': 'name'
      -
        - addMerger
        -
          - '/^[\s\S]*\\routes\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/router': 'id'
              '/config/router/route': 'id'
              '/config/router/route/module': 'name'
      -
        - addMerger
        -
          - '/^[\s\S]*\\menu\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/menu/add': 'id'
      -
        - addMerger
        -
          - '/^[\s\S]*\/acl\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/acl/resources/resource': 'id'
              '/config/acl/resources/resource/resource': 'id'
      -
        - addMerger
        -
          - '/^[\s\S]*\/(base|frontend|adminhtml)\/layout\/.*\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\LayoutMerger'
      -
        - addMerger
        -
          - '/^.*\.php/'
          - '@Orba\Magento2Codegen\Service\FileMerger\PhpMerger'


  Orba\Magento2Codegen\Service\FileMerger\XmlMerger:
    shared: false

  Orba\Magento2Codegen\Service\FileMerger\PhpMerger:
    shared: false

  Orba\Magento2Codegen\Command\Template\GenerateCommand:
    arguments:
      $inputValidators:
        - '@Orba\Magento2Codegen\Service\Input\RootDirValidator'

  Orba\Magento2Codegen\Service\TemplateProcessorInterface:
    class: '\Orba\Magento2Codegen\Service\TwigTemplateProcessor'

  Orba\Magento2Codegen\Service\Twig\FiltersExtension:
    arguments:
      $filters:
        camel: '@Orba\Magento2Codegen\Service\StringFilter\CamelCaseFilter'
        pascal: '@Orba\Magento2Codegen\Service\StringFilter\PascalCaseFilter'
        snake: '@Orba\Magento2Codegen\Service\StringFilter\SnakeCaseFilter'
        kebab: '@Orba\Magento2Codegen\Service\StringFilter\KebabCaseFilter'
        lower_only: '@Orba\Magento2Codegen\Service\StringFilter\LowerOnlyCaseFilter'
        ucfirst: '@Orba\Magento2Codegen\Service\StringFilter\UcfirstFilter'

  Orba\Magento2Codegen\Service\Twig\FunctionsExtension:
    arguments:
      $functions:
        columnDefinition: '@Orba\Magento2Codegen\Service\StringFunction\ColumnDefinitionFunction'
        databaseTypeToPHP: '@Orba\Magento2Codegen\Service\StringFunction\DatabaseTypeToPHPFunction'
        fullTextIndex: '@Orba\Magento2Codegen\Service\StringFunction\FullTextIndexFunction'
        folderScope: '@Orba\Magento2Codegen\Service\StringFunction\FolderScopeFunction'

  Orba\Magento2Codegen\Service\PropertyValueCollector\CollectorFactory:
    arguments:
      $map:
        'Orba\Magento2Codegen\Model\ConstProperty': '@Orba\Magento2Codegen\Service\PropertyValueCollector\ConstCollector'
        'Orba\Magento2Codegen\Model\StringProperty': '@Orba\Magento2Codegen\Service\PropertyValueCollector\StringCollector'
        'Orba\Magento2Codegen\Model\ArrayProperty': '@Orba\Magento2Codegen\Service\PropertyValueCollector\ArrayCollector'

  Orba\Magento2Codegen\Service\PropertyValueCollector\ArrayCollector:
    calls:
      - method: setCollectorFactory
        arguments:
          - '@Orba\Magento2Codegen\Service\PropertyValueCollector\CollectorFactory'

  Orba\Magento2Codegen\Service\PropertyFactory:
    arguments:
      $map:
        const: '@Orba\Magento2Codegen\Service\PropertyFactory\ConstFactory'
        string: '@Orba\Magento2Codegen\Service\PropertyFactory\StringFactory'
        array: '@Orba\Magento2Codegen\Service\PropertyFactory\ArrayFactory'

  Orba\Magento2Codegen\Service\PropertyFactory\ArrayFactory:
    calls:
      - method: setPropertyFactory
        arguments:
          - '@Orba\Magento2Codegen\Service\PropertyFactory'