services:
  _defaults:
    autowire: true

  Symfony\Component\Filesystem\Filesystem:
    class: '\Symfony\Component\Filesystem\Filesystem'

  Symfony\Component\Yaml\Parser:
    class: '\Symfony\Component\Yaml\Parser'

  Symfony\Component\Config\Definition\Processor:
    class: '\Symfony\Component\Config\Definition\Processor'

  Orba\Magento2Codegen\:
    resource: '../src/Orba/Magento2Codegen'
    exclude: '../src/Orba/Magento2Codegen/Test'

  Orba\Magento2Codegen\Application:
    public: true

  Orba\Magento2Codegen\Service\IO:
    public: true

  Orba\Magento2Codegen\Service\FileMergerFactory:
    calls:
      -
        - addMerger
        -
          - '/\/di\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/preference': 'for'
              '/config/(type|virtualType)': 'name'
              '/config/(type|virtualType)/plugin': 'name'
              '/config/(type|virtualType)/arguments/argument': 'name'
              '/config/(type|virtualType)/arguments/argument(/item)+': 'name'
            typeAttributeName: 'xsi:type'
      -
        - addMerger
        -
          - '/\/db_schema\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/schema/table': 'name'
              '/schema/table/column': 'name'
              '/schema/table/constraint': 'referenceId'
              '/schema/table/index': 'referenceId'
              '/schema/table/index/column': 'name'
              '/schema/table/constraint/column': 'name'
      -
        - addMerger
        -
          - '/\/routes\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/router': 'id'
              '/config/router/route': 'id'
              '/config/router/route/module': 'name'
      -
        - addMerger
        -
          - '/\/menu\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/menu/add': 'id'
      -
        - addMerger
        -
          - '/\/acl\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/acl/resources/resource': 'id'
              '/config/acl/resources(/resource)+': 'id'
      -
        - addMerger
        -
          - '/\/system\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/system/tab': 'id'
              '/config/system/section': 'id'
              '/config/system/section/group': 'id'
              '/config/system/section/group/field': 'id'
      -
        - addMerger
        -
          - '/\/cron_groups\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/group': 'id'
      -
        - addMerger
        -
          - '/\/crontab\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/group': 'id'
              '/config/group/job': 'name'
      -
        - addMerger
        -
          - '/\/events\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/event': 'name'
              '/config/event/observer': 'name'
      -
        - addMerger
        -
          - '/\/config\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
      -
        - addMerger
        -
          - '/\/layout\/.*\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/page/update': 'handle'
              '/page/html/attribute': 'name'
              '/page/head/(css|link|font|script|remove)': 'src'
              '/page/head/(attribute|meta)': 'name'
              '/page/body.*/(block|container|uiComponent)': 'name'
              '/page/body.*/block/arguments/argument(/item)*': 'name'
              '/page/body.*/move': 'element'
      -
        - addMerger
        -
          - '/\/extension_attributes\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/extension_attributes': 'for'
              '/config/extension_attributes/attribute': 'code'
            typeAttributeName: 'xsi:type'
      -
        - addMerger
        -
          - '/\/fieldset\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
             idAttributes:
               '/config/scope': 'id'
               '/config/scope/fieldset': 'id'
               '/config/scope/fieldset/field': 'name'
               '/config/scope/fieldset/field/aspect': 'name'
      -
        - addMerger
        -
          - '/\/view\/.*\/ui_component\/.*_form\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/form/argument(/item)*': 'name'
              '/form/dataSource': 'name'
              '/form/dataSource/argument(/item)*': 'name'
              '/form/dataSource/argument/argument(/item)*': 'name'
              '/form/fieldset': 'name'
              '/form/fieldset/argument(/item)*': 'name'
              '/form/fieldset/field': 'name'
              '/form/fieldset/field/argument(/item)*': 'name'
            typeAttributeName: 'xsi:type'
      -
        - addMerger
        -
            - '/\/view\/.*\/ui_component\/.*_listing\.xml$/'
            - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
            -
              idAttributes:
                '/listing/argument(/item)*': 'name'
                '/listing/dataSource': 'name'
                '/listing/dataSource/argument(/item)*': 'name'
                '/listing/dataSource/argument/argument(/item)*': 'name'
                '/listing/container': 'name'
                '/listing/container/argument(/item)*': 'name'
                '/listing/container/(bookmark|component|filterSearch|filters|massaction|paging)': 'name'
                '/listing/container/(bookmark|component|filterSearch|filters|massaction|paging)/argument(/item)*': 'name'
                '/listing/container/massaction/action': 'name'
                '/listing/container/massaction/action/argument(/item)*': 'name'
                '/listing/columns': 'name'
                '/listing/columns/argument(/item)*': 'name'
                '/listing/columns/(selectionsColumn|column|actionsColumn)': 'name'
                '/listing/columns/(selectionsColumn|column|actionsColumn)/argument(/item)*': 'name'
              typeAttributeName: 'xsi:type'
      -
        - addMerger
        -
          - '/\/email_templates\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/template': 'id'
      -
        - addMerger
        -
          - '/\/webapi\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/routes/route': ['url', 'method']
              '/routes/route/resources/resource': 'ref'
              '/routes/route/data/parameter': 'name'
      -
        - addMerger
        -
          - '/\/cache\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/type': 'name'
      -
        - addMerger
        -
          - '/\/module\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/module': 'name'
              '/config/module/sequence/module': 'name'
      -
        - addMerger
        -
          - '/\/widget\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/widgets/widget': 'id'
      -
        - addMerger
        -
          - '/\/communication\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/topic': 'name'
      -
        - addMerger
        -
          - '/\/queue_consumer\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/consumer': 'name'
      -
        - addMerger
        -
          - '/\/queue_publisher\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/publisher': 'topic'
              '/config/publisher/connection': 'name'
      -
        - addMerger
        -
          - '/\/queue_topology\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/exchange': ['name', 'connection']
              '/config/exchange/arguments/argument': 'name'
              '/config/exchange/arguments/argument(/item)+': 'name'
              '/config/exchange/binding': 'id'
              '/config/exchange/binding/arguments/argument': 'name'
              '/config/exchange/binding/arguments/argument(/item)+': 'name'
      -
        - addMerger
        -
          - '/\/app\/etc\/config\.php$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\ConfigPhpMerger'
      -
        - addMerger
        -
          - '/\/import\.xml$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\XmlMerger'
          -
            idAttributes:
              '/config/entity': 'name'
      -
        - addMerger
        -
          - '/^.*\.php/'
          - '@Orba\Magento2Codegen\Service\FileMerger\PhpMerger'
      -
        - addMerger
        -
          - '/\/i18n\/.*\.csv$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\CsvI18nMerger'
      -
        - addMerger
        -
          - '/^.*\.json/'
          - '@Orba\Magento2Codegen\Service\FileMerger\JsonMerger'
      -
        - addMerger
        -
          - '/\/requirejs-config\.js$/'
          - '@Orba\Magento2Codegen\Service\FileMerger\RequirejsConfigMerger'

  Orba\Magento2Codegen\Service\FileMerger\XmlMerger:
    shared: false

  Orba\Magento2Codegen\Service\FileMerger\PhpMerger:
    shared: false

  Orba\Magento2Codegen\Service\FileMerger\JsonMerger:
    shared: false

  Orba\Magento2Codegen\Command\Template\GenerateCommand:
    arguments:
      $inputValidators:
        - '@Orba\Magento2Codegen\Service\Input\RootDirValidator'
        - '@Orba\Magento2Codegen\Service\Input\ForceMergeValidator'

  Orba\Magento2Codegen\Service\TemplateProcessorInterface:
    class: '\Orba\Magento2Codegen\Service\TwigTemplateProcessor'

  Orba\Magento2Codegen\Service\Twig\EscaperExtension\EscaperCollection:
    arguments:
      $escapers:
        csv: '@Orba\Magento2Codegen\Service\Twig\EscaperExtension\CsvEscaper'

  Orba\Magento2Codegen\Service\Twig\FiltersExtension:
    arguments:
      $filters:
        camel: '@Orba\Magento2Codegen\Service\StringFilter\CamelCaseFilter'
        pascal: '@Orba\Magento2Codegen\Service\StringFilter\PascalCaseFilter'
        snake: '@Orba\Magento2Codegen\Service\StringFilter\SnakeCaseFilter'
        kebab: '@Orba\Magento2Codegen\Service\StringFilter\KebabCaseFilter'
        lower_only: '@Orba\Magento2Codegen\Service\StringFilter\LowerOnlyCaseFilter'
        ucfirst: '@Orba\Magento2Codegen\Service\StringFilter\UcfirstFilter'
        pluralize: '@Orba\Magento2Codegen\Service\StringFilter\PluralizeFilter'
        titleize: '@Orba\Magento2Codegen\Service\StringFilter\TitleizeFilter'

  Orba\Magento2Codegen\Service\Twig\FunctionsExtension:
    arguments:
      $functions:
        columnDefinition: '@Orba\Magento2Codegen\Service\StringFunction\ColumnDefinitionFunction'
        databaseTypeToPHP: '@Orba\Magento2Codegen\Service\StringFunction\DatabaseTypeToPHPFunction'
        fullTextIndex: '@Orba\Magento2Codegen\Service\StringFunction\FullTextIndexFunction'
        folderScope: '@Orba\Magento2Codegen\Service\StringFunction\FolderScopeFunction'

  Orba\Magento2Codegen\Service\PropertyValueCollector\CollectorFactory:
    arguments:
      $map:
        'Orba\Magento2Codegen\Model\ConstProperty': '@Orba\Magento2Codegen\Service\PropertyValueCollector\ConstCollector'
        'Orba\Magento2Codegen\Model\StringProperty': '@Orba\Magento2Codegen\Service\PropertyValueCollector\StringCollector'
        'Orba\Magento2Codegen\Model\ArrayProperty': '@Orba\Magento2Codegen\Service\PropertyValueCollector\ArrayCollector'
        'Orba\Magento2Codegen\Model\BooleanProperty': '@Orba\Magento2Codegen\Service\PropertyValueCollector\BooleanCollector'
        'Orba\Magento2Codegen\Model\ChoiceProperty': '@Orba\Magento2Codegen\Service\PropertyValueCollector\ChoiceCollector'

  Orba\Magento2Codegen\Service\PropertyValueCollector\ArrayCollector:
    calls:
      - method: setCollectorFactory
        arguments:
          - '@Orba\Magento2Codegen\Service\PropertyValueCollector\CollectorFactory'

  Orba\Magento2Codegen\Service\PropertyFactory:
    arguments:
      $map:
        const: '@Orba\Magento2Codegen\Service\PropertyFactory\ConstFactory'
        string: '@Orba\Magento2Codegen\Service\PropertyFactory\StringFactory'
        array: '@Orba\Magento2Codegen\Service\PropertyFactory\ArrayFactory'
        boolean: '@Orba\Magento2Codegen\Service\PropertyFactory\BooleanFactory'
        bool: '@Orba\Magento2Codegen\Service\PropertyFactory\BooleanFactory'
        choice: '@Orba\Magento2Codegen\Service\PropertyFactory\ChoiceFactory'

  Orba\Magento2Codegen\Service\PropertyFactory\ArrayFactory:
    calls:
      - method: setPropertyFactory
        arguments:
          - '@Orba\Magento2Codegen\Service\PropertyFactory'

  Orba\Magento2Codegen\Service\TemplateBuilder:
    arguments:
      $templateTypes:
        basic: '@Orba\Magento2Codegen\Service\TemplateType\Basic'
        module: '@Orba\Magento2Codegen\Service\TemplateType\Module'
        root: '@Orba\Magento2Codegen\Service\TemplateType\Root'

  Orba\Magento2Codegen\Service\TemplateType\Module:
    calls:
      - method: setTemplateFactory
        arguments:
          - '@Orba\Magento2Codegen\Service\TemplateFactory'
