dependencies:
  - viewModel
properties:
  frontName:
    type: string
    description: First part of action's URL.
  controllerName:
    type: string
    description: Second part of action's URL. It should be one word.
  actionName:
    type: string
    description: Third part of action's URL.
  pageLayout:
    type: string
    description: Layout type, eg. "1column", "2columns".