type: module
description: This template is used to create new group for already existent section of store configuration.
properties:
  id:
    type: string
    required: true
    description: Group ID
  sectionId:
    type: string
    required: true
    description: Section ID
  label:
    type: string
    required: true
    description: Group label
  sortOrder:
    type: string
    description: sortOrder argument value
  showInDefault:
    type: boolean
    description: showInDefault argument value
    default: true
  showInWebsite:
    type: boolean
    description: showInWebsite argument value
    default: true
  showInStore:
    type: boolean
    description: showInStore argument value
    default: true
