properties:
  sectionId:
    type: string
    description: Section ID
  id:
    type: string
    description: Group ID
  label:
    type: string
    description: Group label
  translate:
    type: string
    description: Translate argument value
    default: label
  type:
    type: string
    description: Group type
    default: text
  sortOrder:
    type: string
    description: sortOrder argument value
  showInDefault:
    type: string
    description: showInDefault argument value
  showInWebsite:
    type: string
    description: showInWebsite argument value
  showInStore:
    type: string
    description: showInStore argument value