description: "This template creates an email template with etc/adminhtml/system.xml etc/config.xml and model/EmailNotification class"
afterGenerate: " 1. Change email template in view/frontend/email/<notificationName>.html\n
                 2. Custom styles can be defined in:\n
                    \tapp/design/frontend/<Vendor>/<theme>/web/css/source/_email-extend.less\n
                    \t.<notificationName>-email-container {\n
                    \t\t//your email styles\n
                    \t}\n
                 3. If new section and group is defined, you can add configuration menu to display config.\n
                 "
properties:
    notificationName:
        type: string
        description: Notification name
        default: Custom notification
    notificationSectionId:
        type: string
        description: "Section id - can be existing or new one (ex.: sales_email)"
        default: sales_email
    notificationGroupId:
        type: string
        description: "Group id - can be existing or new one (ex.: order)"
        default: order
    notificationLabel:
        type: string
        description: Field label
        default: Custom notification email
    notificationComment:
        type: string
        description: Field comment (optional)
        default: Custom notification comment
    notificationSortOrder:
        type: string
        description: Sort order value
        default: 0
    notificationShowInDefault:
        type: boolean
        description: Should field be visible in default config scope?
        default: true
    notificationShowInWebsite:
        type: boolean
        description: Should field be visible in website scope?
        default: true
    notificationShowInStore:
        type: boolean
        description: Should field be visible in store scope?
        default: true
    notificationCanRestore:
        type: boolean
        description: Could default value be restored?
        default: true
    notificationSubject:
        type: string
        description: Email subject
        default: Default notification title
